/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Add Priest of Tempus kit for Priests             \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

BEGIN ~Add Priest of Tempus kit for Priests~
REQUIRE_PREDICATE GAME_IS ~bgee bg2ee eet~ ~This component is not compatible with your game~
REQUIRE_PREDICATE NOT FILE_EXISTS_IN_GAME ~ohtempus.2da~ ~This kit is already in the game~

LOAD_TRA ~EET_Tweaks/lang/%LANGUAGE%/%COMPONENT_NUMBER%.tra~

ACTION_IF GAME_IS ~bgee~ BEGIN
	OUTER_SET kit_biography = 15884
	OUTER_SET kit_briefdesc = 31255
END ELSE ACTION_IF GAME_IS ~bg2ee~ BEGIN
	OUTER_SET kit_biography = ~-1~
	OUTER_SET kit_briefdesc = 102495
END ELSE BEGIN //eet
	OUTER_SET kit_biography = 15884
	OUTER_SET kit_briefdesc = 102495
END

ADD_KIT ~OHTEMPUS~
	// CLASS WEAPON PROFICIENCIES_____
	//                 S L            
	//                 M A            
	//                 A R            
	//                 L G   M        
	//                 L E   I   S    
	//                 S S B S   P   S
	//                 W W L S   I   P
	//                 O O U I B K A E
	//                 R R N L O E X A
	// CLASWEAP.2DA    D D T E W D E R
	~OHTEMPUS          0 0 1 1 0 1 0 0~
	// WEAPON PROFICIENCIES_________________________________________________________________________________________________
	//                                         T   S           F   Q             S S                                        
	//                 L S                     W   C           L   U             W I                                        
	//                 A M             B L S   O   I   W       A   A             O N                                        
	//                 R A             A O H   H   M   A       I   R C   S       R G                                        
	//                 G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
	//                 E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
	//                 S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
	//                 W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
	//                 O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
	//                 R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
	// WEAPPROF.2DA    D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
	~OHTEMPUS          0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	// MINIMUM KIT STATS______________________
	// ABCLASRQ.2DA    STR DEX CON INT WIS CHR
	~OHTEMPUS          0   0   0   0   9   0~
	// KIT STAT MODIFIERS_____________________
	// ABCLSMOD.2DA    STR DEX CON INT WIS CHR
	~OHTEMPUS          0   0   0   0   0   0~
	// REQUIREMENTS TO DUAL TO THIS KIT_______
	// ABDCDSRQ.2DA    STR DEX CON INT WIS CHR
	~OHTEMPUS          0   0   0   0   17  0~
	// REQUIREMENTS TO DUAL FROM THIS KIT_____
	// ABDCSCRQ.2DA    STR DEX CON INT WIS CHR
	~OHTEMPUS          0   0   0   0   15  0~
	// ALIGNMENT RESTRICTIONS____________________
	// ALIGNMNT.2DA    LG LN LE NG TN NE CG CN CE
	~OHTEMPUS          0  0  0  0  1  0  1  1  1~
	// DUAL CLASS OPTIONS_______________
	// DUALCLASS.2DA   FT CL MA TH DR RA
	~OHTEMPUS          1  0  1  1  0  1~
	// KIT ABILITIES 2DA FILE (path to CLAB-type file)
	~EET_Tweaks/%COMPONENT_NUMBER%/OHTEMPUS.2DA~
	// RACIAL KIT AVAILABILITY____________________________________
	//                                                    H       
	//                                             H      A      H
	//                                             A      L      A
	//                 H      D      G             L      F      L
	//                 U      W      N             F      L      F
	//                 M      A      O      E      E      I      O
	//                 A      R      M      L      L      N      R
	// KITTABLE.2DA    N      F      E      F      F      G      C
	~                  K_C_H  K_C_D  K_C_G  K_C_E  K_C_HE K_C_HL K_C_HO~
	// UNUSABLE FLAGS AND KIT BASE CLASS
	// CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5, Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19, Monk = 20
	// KITLIST.2DA
	~                  0x00004000 3~
	// HIGH LEVEL ABILITIES ABBREVIATION
	// LUABBR.2DA
	~                  Cl0~
	// TOB STARTING EQUIPMENT__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
	//                                                                                                                                      B                                                                                                                                 W
	//                              S                                                                C                         A            R                                                                                                                                 E
	//                 A            H                                      R            R            L            B            M            A                         A            A            A            M            M            M            M            M            A
	//                 R            I            H                         I            I            O            O            U            C            B            M            M            M            I            I            I            I            I            P
	//                 M            E            E            B            N            N            A            O            L            E            E            M            M            M            S            S            S            S            S            O
	//                 O            L            L            A            G            G            C            T            E            R            L            O            O            O            C            C            C            C            C            N
	// 25STWEAP.2DA    R            D            M            G            1            2            K            S            T            S            T            1            2            3            1            2            3            4            5            1
	~                  CHAN09       *            HELM07       BAG20        RING06       RING31       *            BOOT01       AMUL19       BRAC16       BELT06       AROW11,40    BULL03,40    BOLT06,40    POTN52,5     POTN04,2     POTN14,5     HAMM07       SW1H27       STAF08~
	// CHARACTER CREATION KIT DESCRIPTION
	// KITLIST.2DA     LOWER
	SAY                @26000000
	// KITLIST.2DA     MIXED
	SAY                @26000001
	// KITLIST.2DA     HELP
	SAY                @26000002

INCLUDE ~EET_Tweaks/lib/fl#add_kit_ee.tpa~
LAF ~fl#add_kit_ee~
	INT_VAR
	//CLASTEXT.2DA       BIOGRAPHY
	    biography     = ~kit_biography~
	//CLASTEXT.2DA       BRIEFDESC
	    briefdesc     = ~kit_briefdesc~
	//CLASTEXT.2DA       FALLEN
	    fallen        = ~0~
	//CLASTEXT.2DA       FALLEN_NOTICE
	    fallen_notice = ~-1~
	STR_VAR
	//internal kit name
	    kit_name      = ~OHTEMPUS~
	//BACKSTAB.2DA       0     1     2     3     4     5     6     7     8     9     10     11     12     13     14     15     16     17     18     19     20     21     22     23     24     25     26     27     28     29     30     31     32     33     34     35     36     37     38     39     40     41     42     43     44     45     46     47     48     49     50
	    //backstab    = ~~
	//CLSWPBON.2DA       GETS_PROF_APR       UNARMED_DIVISOR     ZERO_SKILL_THAC0
	    clswpbon      = ~0                   0                   3~
	//NUMWSLOT.2DA       SLOTS
	    numwslot      = ~2~
	//THIEFSKL.2DA       START_POINTS       LEVEL_POINTS
	    //thiefskl    = ~~
	//TRAPLIMT.2DA       LIMIT
	    //traplimt    = ~~
	//CLASCOLR.2DA       METAL     MINOR_CLOTH     MAIN_CLOTH     LEATHER     ARMOR
	    clascolr      = ~80        126             127            93          97~
	//CLASISKL.2DA       PICK_POCKETS     OPEN_LOCKS     FIND_TRAPS     MOVE_SILENTLY     HIDE_IN_SHADOWS     DETECT_ILLUSION     SET_TRAPS
	    clasiskl      = ~0                0              0              0                 0                   0                   0~
	//THIEFSCL.2DA       PICK_POCKETS     OPEN_LOCKS     FIND_TRAPS     MOVE_SILENTLY     HIDE_IN_SHADOWS     DETECT_ILLUSION     SET_TRAPS     STEALTH
	    thiefscl      = ~0                0              0              0                 0                   0                   0             0~
	//HPCLASS.2DA        TABLE
	    hpclass       = ~HPPRS~
	//CLSRCREQ.2DA       HUMAN               ELF                 HALF_ELF            DWARF               HALFLING            GNOME               HALFORC
	    clsrcreq      = ~1                   1                   1                   1                   1                   1                   1~
	//CLASTHAC.2DA       BONUS
	    clasthac      = ~0~
	//SNEAKATT.2DA       0     1     2     3     4     5     6     7     8     9     10     11     12     13     14     15     16     17     18     19     20     21     22     23     24     25     26     27     28     29     30     31     32     33     34     35     36     37     38     39     40     41     42     43     44     45     46     47     48     49     50
	    //sneakatt    = ~~
	//CRIPPSTR.2DA       0     1     2     3     4     5     6     7     8     9     10     11     12     13     14     15     16     17     18     19     20     21     22     23     24     25     26     27     28     29     30     31     32     33     34     35     36     37     38     39     40     41     42     43     44     45     46     47     48     49     50
	    //crippstr    = ~~
END

ACTION_FOR_EACH file IN CLASWEAP WEAPPROF ABCLASRQ ABCLSMOD ABDCDSRQ ABDCSCRQ ALIGNMNT DUALCLAS KITTABLE KITLIST LUABBR 25STWEAP CLASTEXT BACKSTAB CLSWPBON NUMWSLOT THIEFSKL TRAPLIMT CLASCOLR CLASISKL THIEFSCL HPCLASS CLSRCREQ CLASTHAC SNEAKATT CRIPPSTR K_C_H K_C_D K_C_G K_C_E K_C_HE K_C_HL K_C_HO BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ BEGIN
		COPY_EXISTING ~%file%.2da~ ~override~
			PRETTY_PRINT_2DA
		BUT_ONLY
	END
END

COPY ~EET_Tweaks/%COMPONENT_NUMBER%/ohtmps1.spl~ ~override~
	SAY 0x8 @26000003
	SAY 0x50 @26000004

COPY ~EET_Tweaks/%COMPONENT_NUMBER%/ohtmps2.spl~ ~override~
	SAY 0x8 @26000005
	SAY 0x50 @26000006

ADD_PROJECTILE ~EET_Tweaks/%COMPONENT_NUMBER%/ohvrpo.PRO~
COPY ~EET_Tweaks/%COMPONENT_NUMBER%/ohtmps2d.spl~ ~override~
	PATCH_FOR_EACH offset IN 0x1ce 0x4ce 0x7ce 0xace 0xdce BEGIN
		SAY offset @26000007
	END
	PATCH_FOR_EACH offset IN 0x98 0xc0 0xe8 0x110 0x138 BEGIN
		WRITE_SHORT offset ohvrpo
	END

ADD_PROJECTILE ~EET_Tweaks/%COMPONENT_NUMBER%/ohvrnp.PRO~
COPY ~EET_Tweaks/%COMPONENT_NUMBER%/ohtmps2e.spl~ ~override~
	PATCH_FOR_EACH offset IN 0x1ce 0x4ce 0x7ce 0xace 0xdce BEGIN
		SAY offset @26000008
	END
	PATCH_FOR_EACH offset IN 0x98 0xc0 0xe8 0x110 0x138 BEGIN
		WRITE_SHORT offset ohvrnp
	END

COPY ~EET_Tweaks/%COMPONENT_NUMBER%/OHTMPSHS.spl~ ~override~

COPY ~EET_Tweaks/%COMPONENT_NUMBER%/OHTMPSHS.itm~ ~override~
	SAY 0xc @25000009
	SAY 0x54 @25000010

ACTION_FOR_EACH ext IN BAM VVC WAV BEGIN
	ACTION_BASH_FOR ~EET_Tweaks/%COMPONENT_NUMBER%~ ~.*\.%ext%$~ BEGIN
		ACTION_IF NOT FILE_EXISTS_IN_GAME ~%BASH_FOR_FILE%~ BEGIN
			COPY ~%BASH_FOR_FILESPEC%~ ~override~
		END
	END
END

COPY ~EET_Tweaks/%COMPONENT_NUMBER%/OHTEMPUS.2DA~ ~override~