

DEFINE_ACTION_FUNCTION move_npc_sharteel_ee
BEGIN
   LAF get_area_script STR_VAR area= ~%MutaminsGarden%~ RET script=script END
   LAF swap_text STR_VAR files= ~%script%.bcs~ swaps=~SetGlobal=>SETGLOBALPLACEHOLDER Global("SHARTEELFIGHT","GLOBAL",[12])=>False() SETGLOBALPLACEHOLDER=>SetGlobal~ END
   LAF extend_area_script STR_VAR area= ~%NorthNashkelRoad%~ top=sharteel_ee location=resource END
END

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
  LAF move_npc_sharteel_ee END
END